input {
  beats {
    port => 5044
  }
}

filter {
  if [message] {
    json {
      source => "message"
      skip_on_invalid_json => true
    }
  }

  if [trace_id] {
    mutate {
      rename => { "trace_id" => "[@metadata][trace_id]" }
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "logs-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}
